### ISSUE TITLE
How to get IR, RGB and Depth images from zense_cam_demo.py

### ISSUE THREAD

**Issue by SumingNTUT** [Vzense/BaseSDK_python_wrapper#2]
how to get IR, RGB and Depth images from zense_cam_demo.py
when I print 
```
frameready = camera.read_next_frame(handle)
print('frame ready:',(frameready.depth, frameready.ir, frameready.rgb)) 
```
get:
`frame ready: (1, 0, 0)`

I have tried `set_data_mode` function, it's Not working

how can I get IR, RGB and Depth images

**Comment by peter-vzense** [comment]
Based on the default code, the datamode is rgb+depth, did it work? @SumingNTUT

**Comment by SumingNTUT** [comment]
@peter-vzense 
No I tried the following every model
```
class DataMode(Enum):
    DEPTH_AND_RGB_30    = 0
    IR_AND_RGB_30       = 1
    DEPTH_AND_IR_30     = 2
    STANDBY             = 102
```
get :
`frame ready: (1, 0, 0)` 
or 
`frame ready: (1, 1, 0)`

**Comment by peter-vzense** [comment]
1. this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. 
2. the datamode is described by the frame, the DEPTH_AND_RGB_30 mean the camera output depth and RGB frame in 30fps. if you want to use depth+ir+rgb, you need to change to the correct mode. And you can reference the new commit.
3. this repo is an open-source project for user can use base sdk in python way. But do not have the whole functions and detailed description. so I advise that you can read the document in the BaseSDK repo.
@SumingNTUT

**Comment by peter-vzense** [comment]
1. this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. 
2. the datamode is described by the frame, the DEPTH_AND_RGB_30 mean the camera output depth and RGB frame in 30fps. if you want to use depth+ir+rgb, you need to change to the correct mode. And you can reference the new commit.
3. this repo is an open-source project for user can use base sdk in python way. But do not have the whole functions and detailed description. so I advise that you can read the document in the BaseSDK repo.
@SumingNTUT

**Comment by SumingNTUT** [comment]
Hi @peter-vzense  

it's working

Thank you
