### ISSUE TITLE
Cannot show RGB image 

### ISSUE THREAD

**Issue by cxjwxy521** [Vzense/BaseSDK_python_wrapper#3]
I have changed the data mode to ir_rgb_depth but there were only two windows (IR and depth).
![捕获](https://user-images.githubusercontent.com/90295256/132456127-c749326d-ce1e-402c-996b-c691cae7d18f.PNG)
![2](https://user-images.githubusercontent.com/90295256/132456141-b8f7b0f6-34b8-4d5f-b780-8e1bba10a094.PNG)

**Comment by peter-vzense** [comment]
this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. @cxjwxy521

**Comment by cxjwxy521** [comment]
> this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. @cxjwxy521
Hi, where is the newest SDK lib for python?

**Comment by peter-vzense** [comment]
> > this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. @cxjwxy521
> > Hi, where is the newest SDK lib for python? @peterliu-pico

this repo is a wrapper, use the linux lib that is a .so file. you could find the correct lib and replace it. @cxjwxy521 
this base sdk link is ：
https://github.com/Vzense/Vzense_SDK_Windows
https://github.com/Vzense/Vzense_SDK_Linux

**Comment by cxjwxy521** [comment]
> > > this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. @cxjwxy521
> > > Hi, where is the newest SDK lib for python? @peterliu-pico
> 
> this repo is a wrapper, use the linux lib that is a .so file. you could find the correct lib and replace it. @cxjwxy521
> this base sdk link is ：
> https://github.com/Vzense/Vzense_SDK_Windows
> https://github.com/Vzense/Vzense_SDK_Linux
![image](https://user-images.githubusercontent.com/90295256/132787555-7c4b51cb-9aa8-4d5a-8c5c-076d9bf7256f.png)
There are four libs, which should I use? Actually I have tried each of them and did not solve the problem. @peter-vzense

**Comment by peter-vzense** [comment]
> > > > this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. @cxjwxy521
> > > > Hi, where is the newest SDK lib for python? @peterliu-pico
> > 
> > 
> > this repo is a wrapper, use the linux lib that is a .so file. you could find the correct lib and replace it. @cxjwxy521
> > this base sdk link is ：
> > https://github.com/Vzense/Vzense_SDK_Windows
> > https://github.com/Vzense/Vzense_SDK_Linux
> > ![image](https://user-images.githubusercontent.com/90295256/132787555-7c4b51cb-9aa8-4d5a-8c5c-076d9bf7256f.png)
> > There are four libs, which should I use? Actually I have tried each of them and did not solve the problem. And should I change the code for the demo?@peter-vzense  And there is only one .lib file in the lib_SDK_Windows, how should I call it?
there are for different platform just like the folder name.
what about your firmware verssion? you could upgrade it to the newest one. 
The firmare and the tool you could find them on:
https://github.com/Vzense/DeviceFirmware-List/tree/master/DCAM710
https://github.com/Vzense/VzenseUpgradeTool

**Comment by cxjwxy521** [comment]
> > > > > this project use old base SDK lib, replace it to the newest SDK lib is the recommended choice. @cxjwxy521
> > > > > Hi, where is the newest SDK lib for python? @peterliu-pico
> > > 
> > > 
> > > this repo is a wrapper, use the linux lib that is a .so file. you could find the correct lib and replace it. @cxjwxy521
> > > this base sdk link is ：
> > > https://github.com/Vzense/Vzense_SDK_Windows
> > > https://github.com/Vzense/Vzense_SDK_Linux
> > > ![image](https://user-images.githubusercontent.com/90295256/132787555-7c4b51cb-9aa8-4d5a-8c5c-076d9bf7256f.png)
> > > There are four libs, which should I use? Actually I have tried each of them and did not solve the problem. And should I change the code for the demo?@peter-vzense  And there is only one .lib file in the lib_SDK_Windows, how should I call it?
> > > there are for different platform just like the folder name.
> > > what about your firmware verssion? you could upgrade it to the newest one.
> > > The firmare and the tool you could find them on:
> > > https://github.com/Vzense/DeviceFirmware-List/tree/master/DCAM710
> > > https://github.com/Vzense/VzenseUpgradeTool

I have solved the problem, thanks!
