### ISSUE TITLE
retrieving and storing poincloud data with different parameters.  

### ISSUE THREAD

**Issue by madinwei** [Vzense/BaseSDK_python_wrapper#6]
Hello @peter-vzense , 
I want to store point clouds in the upright coordinate system (Z is up, Y is forward, X is right-ward) and to change the scale of X, Y and Z for the saved Pointcloud. I have checked PointCloudCaptureAndSave.py but I am a bit lost.
Is it possible if you give some guides or advise on how to do it.

thank you in advance.
Best,,,,

**Comment by Neal-Shen** [comment]
**to change the scale of X, Y and Z**

as follow:

ret, pointlist = camera.Ps2_ConvertDepthFrameToWorldVector(frame)
if  ret == 0:
    scale =0.01
    for i in range(frame.width*frame.height):
          if pointlist[i].z!=0 and pointlist[i].z!=65535:
                 pointlist[i].x *= scale 
                 pointlist[i].y *= scale 
                 pointlist[i].z *= scale
