### ISSUE TITLE
viewing Pointcloud captured by camera

### ISSUE THREAD

**Issue by madinwei** [Vzense/BaseSDK_python_wrapper#7]
Hello, @peter-vzense , @neal-vzense 

I am trying to viz the pointcloud as part of my inference of my model. do you have a sample example or can you provide me with any advice on the matter?

**Comment by Neal-Shen** [comment]
Hello, madinwei

I modiy the "**PointCloudCaptureAndSave.cpp**" for your case, and have verified  with DCAM560C in ubuntu18.04 ( python3.9.7  and open3d)
[PointCloudCaptureAndSave.zip](https://github.com/Vzense/BaseSDK_python_wrapper/files/10358068/PointCloudCaptureAndSave.zip)
